# It contains all the configs required in the project

data:
  local_dir: hymenoptera_data
  data_url: "https://download.pytorch.org/tutorial/hymenoptera_data.zip"
  data_zip_folder: "data.zip"
  unzip_folder_name: "data"

model:
  train_path_folder: hymenoptera_data\train
  test_path_folder: hymenoptera_data\val
  img_size: [224,224]
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  batch_size: 64
  num_epoch: 10
  model_save: transfer-model.pth
