# It contains all the configs required in the project

data:
  local_dir: hymenoptera_data
  data_url: "https://download.pytorch.org/tutorial/hymenoptera_data.zip"
  data_zip_folder: "data.zip"
  unzip_folder_name: "data"
